language: node_js

node_js:
 - "12"
 - "14"
 - "16"

install:
- CXX="g++-4.8" CC="gcc-4.8" npm install

# thanks to http://stackoverflow.com/a/30925448/1283667:
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
