os: Visual Studio 2015

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

# environment variables
environment:
  NODE_PRE_GYP_GITHUB_TOKEN:
    secure: JIFkGFpWcdJz5bD8hoc9GaCwUIV2openq0IDowt9DRfc8/guS/HTQdjru0Zrb0Dg

  matrix:
  - nodejs_version: "0.10"
  - nodejs_version: "0.12"
  - nodejs_version: 4
  - nodejs_version: 6
  - nodejs_version: 7

# to add several platforms to build matrix:
platform:
  - x86
  - x64

install:
  - cmd: ECHO "%nodejs_version%"
  - cmd: ECHO "%platform%"
  - cmd: ECHO "%APPVEYOR_REPO_COMMIT_MESSAGE%"

  - cmd: SET PATH=%cd%\node_modules\.bin\;%PATH%
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform

  - ps: >
      if (($env:nodejs_version -eq "0.10") -or ($env:nodejs_version -eq "0.12")) {
        $env:install_global = "npm install -g"
        $env:install_local = "npm install"
      } else {
        $env:install_global = "yarn global add"
        $env:install_local = "yarn"
      }
      true;

  - cmd: "%install_global% npm"

  - cmd: SET COMMIT_MSG="%APPVEYOR_REPO_COMMIT_MESSAGE%"
  - cmd: SET PUBLISH_BINARY=false
  # Check to verify the branch is the same than latest tag, if so
  # then we publish the binaries if everything else is successful.
  - cmd: git describe --tags --always HEAD > _git_tag.tmp
  - cmd: SET /p GIT_TAG=<_git_tag.tmp
  - cmd: ECHO %GIT_TAG%
  - cmd: ECHO %APPVEYOR_REPO_BRANCH%
  - cmd: DEL _git_tag.tmp
  - cmd: IF x%APPVEYOR_REPO_BRANCH%==x%GIT_TAG% SET PUBLISH_BINARY=true
  # Or look for commit message containing `[publish binary]`
  - cmd: IF not x%COMMIT_MSG:[publish binary]=%==x%COMMIT_MSG% SET PUBLISH_BINARY=true
  - cmd: ECHO %PUBLISH_BINARY%

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: "%install_local% --build-from-source --msvs_version=2015"

on_success:
  - cmd: IF %PUBLISH_BINARY%==true (node-pre-gyp package 2>&1)
  - cmd: IF %PUBLISH_BINARY%==true (node-pre-gyp-github publish --release 2>&1)
  - cmd: IF %PUBLISH_BINARY%==true (node-pre-gyp clean)
  - cmd: IF %PUBLISH_BINARY%==true (%install_local% --fallback-to-build=false)

test: OFF
deploy: OFF
